# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{monglogg}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Łukasz Sągol"]
  s.date = %q{2011-01-08}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{lukasz@sagol.pl}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "lib/monggler.rb",
    "lib/monggler/helper.rb",
    "lib/monggler/log_subscribers/action_controller_subscriber.rb",
    "lib/monggler/log_subscribers/action_view_subscriber.rb",
    "lib/monggler/log_subscribers/active_record_subscriber.rb",
    "lib/monggler/logger.rb",
    "lib/monggler/mongo_driver.rb",
    "test/dummy/Rakefile",
    "test/dummy/app/controllers/application_controller.rb",
    "test/dummy/app/controllers/items_controller.rb",
    "test/dummy/app/helpers/application_helper.rb",
    "test/dummy/app/helpers/items_helper.rb",
    "test/dummy/app/models/item.rb",
    "test/dummy/app/views/items/_form.html.erb",
    "test/dummy/app/views/items/_item.html.erb",
    "test/dummy/app/views/items/_new_item.html.erb",
    "test/dummy/app/views/items/edit.html.erb",
    "test/dummy/app/views/items/index.html.erb",
    "test/dummy/app/views/items/new.html.erb",
    "test/dummy/app/views/items/show.html.erb",
    "test/dummy/app/views/layouts/application.html.erb",
    "test/dummy/config.ru",
    "test/dummy/config/application.rb",
    "test/dummy/config/boot.rb",
    "test/dummy/config/database.yml",
    "test/dummy/config/environment.rb",
    "test/dummy/config/environments/development.rb",
    "test/dummy/config/environments/production.rb",
    "test/dummy/config/environments/test.rb",
    "test/dummy/config/initializers/backtrace_silencers.rb",
    "test/dummy/config/initializers/inflections.rb",
    "test/dummy/config/initializers/mime_types.rb",
    "test/dummy/config/initializers/secret_token.rb",
    "test/dummy/config/initializers/session_store.rb",
    "test/dummy/config/locales/en.yml",
    "test/dummy/config/routes.rb",
    "test/dummy/db/migrate/20110108193231_create_items.rb",
    "test/dummy/db/schema.rb",
    "test/dummy/db/test.sqlite3",
    "test/dummy/public/404.html",
    "test/dummy/public/422.html",
    "test/dummy/public/500.html",
    "test/dummy/public/favicon.ico",
    "test/dummy/public/javascripts/application.js",
    "test/dummy/public/javascripts/controls.js",
    "test/dummy/public/javascripts/dragdrop.js",
    "test/dummy/public/javascripts/effects.js",
    "test/dummy/public/javascripts/prototype.js",
    "test/dummy/public/javascripts/rails.js",
    "test/dummy/public/stylesheets/.gitkeep",
    "test/dummy/public/stylesheets/scaffold.css",
    "test/dummy/script/rails",
    "test/helper.rb",
    "test/test_active_record_subscriber.rb",
    "test/test_items_controller.rb",
    "test/test_logger.rb",
    "test/test_monggler.rb",
    "test/test_mongo_driver.rb"
  ]
  s.homepage = %q{http://github.com/zgryw/monglogg}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Monglogg allows Rails to log straight into MongoDB}
  s.test_files = [
    "test/dummy/app/controllers/application_controller.rb",
    "test/dummy/app/controllers/items_controller.rb",
    "test/dummy/app/helpers/application_helper.rb",
    "test/dummy/app/helpers/items_helper.rb",
    "test/dummy/app/models/item.rb",
    "test/dummy/config/application.rb",
    "test/dummy/config/boot.rb",
    "test/dummy/config/environment.rb",
    "test/dummy/config/environments/development.rb",
    "test/dummy/config/environments/production.rb",
    "test/dummy/config/environments/test.rb",
    "test/dummy/config/initializers/backtrace_silencers.rb",
    "test/dummy/config/initializers/inflections.rb",
    "test/dummy/config/initializers/mime_types.rb",
    "test/dummy/config/initializers/secret_token.rb",
    "test/dummy/config/initializers/session_store.rb",
    "test/dummy/config/routes.rb",
    "test/dummy/db/migrate/20110108193231_create_items.rb",
    "test/dummy/db/schema.rb",
    "test/helper.rb",
    "test/test_active_record_subscriber.rb",
    "test/test_items_controller.rb",
    "test/test_logger.rb",
    "test/test_monggler.rb",
    "test/test_mongo_driver.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<mongo>, [">= 0"])
      s.add_runtime_dependency(%q<bson_ext>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<mongo>, [">= 0"])
      s.add_dependency(%q<bson_ext>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<mongo>, [">= 0"])
    s.add_dependency(%q<bson_ext>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
  end
end

